[package]
name = 'palette'
version = '0.1.0'
edition = '2021'

[dependencies]
yew = { git = "https://github.com/yewstack/yew/" }
palette-macros = { path = "../palette-macros" }

[dev-dependencies]
cucumber = '0.13'
